### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by xdsopl** [aicodix/rattlegram#38]
Hey @IzzySoft, I hope Rattlegram v1.16 has enough determinism to pass your tests. If not, please tell me what we can do to make things better.

**Comment by IzzySoft** [comment]
I cannot tell, sorry: the APK was built from a commit that does not exist here, b6b61bf1c69b177ea34dcb509c66fc66c66a2e3e according to `META-INF/version-control-info.textproto`:

```yaml
repositories {
  system: GIT
  local_root_path: "$PROJECT_DIR"
  revision: "b6b61bf1c69b177ea34dcb509c66fc66c66a2e3e"
}
```

![Image](https://github.com/user-attachments/assets/c2ef9d7b-43c4-41a4-aa73-4b5158708368)

Unfortunately, that's the commit taking care for versioning, so I cannot simply patch that file… Could you please push that commit?
